version: '3.8'

services:
    flask-server-api:
        build: ./server
        ports: 
            - 8000:5000
        volumes:
            - ./server/src:/app/src:rw

    vue-client-app:
        build: ./client
        ports: 
            - 8001:5173
        volumes:
            - ./client/src:/app/src:rw