version: '3.8'

services:

    vue-client-app:
        build: ./client
        ports: 
            - 8001:3000
        volumes:
            - ./client/src:/app/src
        restart: unless-stopped
    
    flask-server-api:
        build: ./server
        ports: 
            - 8000:5000
        volumes:
            - ./server/src:/app/src
        restart: unless-stopped
        environment:
            DB_HOST: db
            DB_USER: backend
            DB_PASSWORD: test
            DB_NAME: flask_db
        depends_on:
            - db

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql-data:/var/lib/mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: flask_db
            MYSQL_USER: backend
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test

    adminer:
        image: adminer
        restart: always
        ports:
            - 8002:8080
        depends_on:
            - db

volumes:
    mysql-data:
        driver: local